name: Update Indexcd .

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.3.1'

      - name: Checkout Helm Packages Repo
        uses: actions/checkout@v2
        with:
          repository: "thawp99/helm_package_internal" # replace "username" with your GitHub username
          token: ${{ secrets.ACTION_TOKEN }}
          path: ./helm_package_internal
  
      - name: Commit and Push Package to GitHub
        run: |
          cd ./helm_package_internal
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          helm repo index .  # update Helm repo index
          git add index
          git commit -m "Update index"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

