name: Update Index

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.3.1'

      # - name: Checkout Helm Packages Repo
      #   uses: actions/checkout@v2
      #   with:
      #     repository: "thawp99/helm_package_internal" # replace "username" with your GitHub username
      #     token: ${{ secrets.ACTION_TOKEN }}
      #     path: ./helm_package_internal

      - name: List files
        run: ls -l
      
      - name: Get name of last pushed package
        id: get_package_name
        run: |
          PACKAGE_NAME=$(ls -ltr *.tgz|tail -n1|awk '{print $NF}')
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Commit and Push Package to GitHub
        run: |
          cd ./helm_package_internal
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          helm repo index .  # update Helm repo index
          git commit -a -m "Update index $PACKAGE_NAME"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          
      # - name: Get name of last pushed package
      #   id: get_package_name
      #   run: |
      #     PACKAGE_NAME=$(ls -t ./helm_package_internal/*.tgz | head -n1 | xargs -n 1 basename)
      #     echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
  
      # - name: Update commit messageb  
      #   run: |
      #     cd ./helm_package_internal
      #     git config user.name "GitHub Actions"
      #     git config user.email "github-actions@github.com"
      #     git commit --amend -m "Update index $PACKAGE_NAME"
      #     git push --force
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
