name: Update Index

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Update Index
        run: |
          helm repo index .
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add index.yaml
          git commit -m "Update chart index"
          git push

